#!/bin/bash
clear;x=20
while true; do
 if [ -f $(ps w|grep host.run|grep ssh|grep 80|awk '{print $1}') ]; then
x=0;rm -rf /root/logremot.txt;echo "tunggu..." > /root/logremot.txt
rm -rf /root/.ssh/known_hosts
screen -dmS remote -L -Logfile /root/logremot.txt ssh -i ~/.ssh/id_xderm -o StrictHostKeyChecking=no -R 80:localhost:80 localhost.run
 fi
 while [ $x -lt 20 ]; do
host=$(cat /root/logremot.txt|grep tunneled|awk '{print $1}')
 if [ $x -eq 19 ]; then
kill $(ps w|grep host.run|grep ssh|awk '{print $1}') 2>/dev/null
x=20;break
 fi
  if [ ! -f $host ]; then
echo "Sedang memperbarui link alternatif...." >> /root/logremot.txt
 fi
TOKEN_BOT=""
CHAT_ID=""
PESAN="Id server: <b>$(hostname)</b>%0ALink: $host"
curl -s -X POST "https://api.telegram.org/bot$TOKEN_BOT/sendmessage" -d "chat_id=$CHAT_ID" -d "parse_mode=html" -d "text=$PESAN"
clear; sleep 2
echo "Sukses dikirim ke telegram anda..."
echo "Host: $host";x=20;break
  fi
sleep 1;((x++))
 done
sleep 1
done
